POST http://localhost:5000/api/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWQ2NjFkMTgzOTJjMDMzMDliYjY0OCIsImlhdCI6MTYzNTU4NzY3OSwiZXhwIjoxNjM1Njc0MDc5fQ.uaGsVRXO6GRjSnNMwLSAuxa-Zos41FsafYUlBhiR9tc

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "user01@gmail.com",
    "password": "123123"
}